### PR TITLE
* fixing typo in case sensitive string causing invalid path

### PR DESCRIPTION
**Pull request by igorsantos07**

### CODE REVIEW

**Comment by igorsantos07** [comment]
quick bug, quick fix, quick PR, quick merge. hahaha that's great.

**Comment by schmunk42** [comment]
:) I put it also on packagist, show give you the new version with @dev almost instantly.
On packages.phundament.com it may take up to 10 minutes.
Let me know if you need a tag to indicate a stable version.

**Comment by igorsantos07** [comment]
I'll probably ask a new minor version after I fix a bunch of bugs/ideas I'm
finding here, so I'll be able to deploy (:

_Igor Santos_
Programador PHP / Ruby
igorsantos.com.br http://www.igorsantos.com.br || memelinks.com

**Comment by igorsantos07** [comment]
Just noticed: there's no need of a new version for this for me to deploy.
In fact, there's even no need for gii-template-collection to stay in the
"require" section of the composer.json file - it should be in the
require-dev section by default. What do you think?

_Igor Santos_
Programador PHP / Ruby
igorsantos.com.br http://www.igorsantos.com.br || memelinks.com

**Comment by schmunk42** [comment]
Yes, it _should_ ... but.
Some of my CRUDs need the Relation widget, therefore the require. But it _should_ even be required by p3media, ... 

And the smaller components, _should_ be in a smaller repo, maybe together with CSaveRelationsBehavior. I just hadn't had the time yet - and also wanted to update their class names :)

What do you think about this change?

**Comment by igorsantos07** [comment]
What do you mean by smaller components?

And I yet didn't had time to see what CSaveRelationsBehavior is (although
I'm pretty sure of what it does, I dunno how to use it yet). But I should
say that I did like the issue where this behavior should he removed from
models without many_many's (:

So I'm not sure if I can opinate here, sorry .-.

**Comment by schmunk42** [comment]
> What do you mean by smaller components?
> Just the two components, not the complete gtc repo.

I was just thinking loud :)

**Comment by igorsantos07** [comment]
Hahaha OK!
I liked P3 and I'm willing to contribute when I get more used to it. I have
some ideas and opinions, but better share/discuss them later when I'm more
experienced with the tool (:

**Comment by igorsantos07** [comment]
OMG I got that now!

Yeah, surely those components should be in another repository. There's no
point on requiring the entire GTC package if you only need something it
depends on - you depend on them too, but not in the GTC (:

_Igor Santos_
Programador PHP / Ruby
igorsantos.com.br http://www.igorsantos.com.br || memelinks.com

**Pull request merged**
