### PR TITLE
Fixed datepicker language defintion

### PR DESCRIPTION
**Pull request by uldisn**
I have idea add links to documentation for widgets . Example add to date picker

### CODE REVIEW

**Comment by schmunk42** [comment]
Nice.

I like the idea of documentation hints, but wouldn't it be more suitable to have a list of widgets and generators in the [wiki](https://github.com/schmunk42/gii-template-collection/wiki). Having it in the source tends to blow up the outputted code.

**Comment by uldisn** [comment]
Most usable is one direct jump.

**Comment by schmunk42** [comment]
@motin Any thoughts on this?

**Comment by motin** [comment]
I too believe that such documentation should be in the wiki rather in the source code. Personally I only use source code comments to explain logic that is not evident at first glance, due to special circumstances or similar.

**Comment by uldisn** [comment]
Links to documentation are not documentation.
One jump from code to widget documentation is very useful.
For beginners that is very actual.

**Comment by motin** [comment]
> Links to documentation are not documentation.

Sorry, I mean documentation hints :)
As we generate tens or hundreds of files, we would get repeated documentation hints. A thorough list in the wiki with what generators do what and how, with proper links to upstream documentation, would be a better way to ensure that beginners understand how gtc works and how to use the generated code.

**Comment by schmunk42** [comment]
I am not decided yet. 

But please have a look at: https://github.com/schmunk42/gii-template-collection/wiki
I just stared this list, structure and contents have to be improved.

**Pull request closed without merging**
