### PR TITLE
Implemented ENUM

### PR DESCRIPTION
**Pull request by uldisn**
BaseModule:
- enum constants
- enum value labels
- enum  lists

Crud enum column
- lisbox filter
- value as label
- editable

### CODE REVIEW

**Comment by schmunk42** [comment]
@uldisn Sorry for the delay, why did you create a new PR?

**Comment by uldisn** [comment]
After first PR I added some fixes and think is better include all changes in one PR.

**Comment by schmunk42** [comment]
OK, thank you!

**Comment by motin** [comment]
@uldisn In case you didn't know: if you push to a branch specific to the pr, then you can push more commits to the same branch and update existing prs

**Pull request merged**
