### PR TITLE
Improved translations

### PR DESCRIPTION
**Pull request by uldisn**
Created Full module and separate messages catalog for static and custom messages

### CODE REVIEW

**Comment by schmunk42** [comment]
Great idea! I'll merge that right away.

**Comment by schmunk42** [comment]
btw: Would be nice, if you could split a feature like the fullModule into a separate PR, next time ;)

**Comment by uldisn** [comment]
Sorry!
I am a beginner in Github.

**Comment by schmunk42** [comment]
No problem, I just noticed it.
Looking forward to more PRs for you. Thanks!

**Pull request merged**
